Repository Derroylo/gitpod-tool, pull requests merged in 2023-09, with the labels that each got.

#3 Add Shortcut (-d) for detached mode (Issue #1)
  README.md
  commands/services/StartServicesCommand.cs
Labels: enhancement

#4 Add dockerComposeFile Config option (Issue #2)
  README.md
  classes/configuration/ServiceConfiguration.cs
  commands/services/ListServicesCommand.cs
  commands/services/SelectServicesCommand.cs
  commands/services/StartServicesCommand.cs
  commands/services/StopServicesCommand.cs
  helper/DockerComposeHelper.cs
Labels: enhancement

#19 Corrects a wrong folder dir in the update script
  gpt.sh
Labels: bug

#20 Update Readme
  README.md
Labels: documentation

#22 Fix the NullReferenceException while checking for available Versions
  Program.cs
  helper/GptUpdateHelper.cs
Labels: bug

#28 Implemented the xdebug setting command
  Program.cs
  commands/php/PhpDebugCommand.cs
  helper/PhpHelper.cs
  helper/php/DebugHelper.cs
Labels: enhancement
